[versions]
compiler = "1.1.1"
gson = "2.10.1"
hiltAndroid = "2.49"
hiltCompiler = "2.49"
hiltNavigationFragment = "1.2.0"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
kotlinxCoroutinesAndroid = "1.8.0"
loggingInterceptor = "4.9.0"
material = "1.12.0"
constraintlayout = "2.2.0"
navigationUiKtx = "2.8.5"
okhttp = "4.10.0"
playServicesMaps = "19.0.0"
retrofit = "2.9.0"
roomRuntime = "2.6.1"
roomCompiler = "2.6.1"
sdpAndroid = "1.1.0"
workRuntimeKtx = "2.10.0"
hiltWork = "1.1.0"
playServicesLocation = "21.3.0"
activityVersion = "1.10.1"
kotlin = "2.0.0"
biometric = "1.1.0"
androidx-core = "1.12.0"
kotlinx-coroutines = "1.8.0"

firebase-messaging = "24.1.2"
firebase-core = "22.5.0"
firebaseBom = "33.16.0"


[libraries]
adapter-rxjava2 = { module = "com.squareup.retrofit2:adapter-rxjava2", version.ref = "retrofit" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core = { group = "androidx.core", name = "core", version.ref = "androidx-core" }
kotlinx-coroutines-guava = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-guava", version.ref = "kotlinx-coroutines" }

androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationUiKtx" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationUiKtx" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "roomRuntime" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
compiler = { module = "android.arch.persistence.room:compiler", version.ref = "compiler" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore-ktx" }

androidx-biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }

gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesAndroid" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMaps" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
sdp-android = { module = "com.intuit.sdp:sdp-android", version.ref = "sdpAndroid" }
androidx-hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hiltWork" }

hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltCompiler" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
androidx-hilt-navigation-fragment = { module = "androidx.hilt:hilt-navigation-fragment", version.ref = "hiltNavigationFragment" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activityVersion" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }

firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebase-messaging" }
firebase-core = { module = "com.google.firebase:firebase-analytics", version.ref = "firebase-core" }


[plugins]
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

